### PR TITLE
Questions UI

### PR DESCRIPTION
**Pull request by TheAndreiUrsu**
# Summary
This PR will merge the UI changes done on the questions page.

# Images

## FIRST SECTION
image

## SECOND SECTION
image

## THIRD SECTION
image

## FOURTH SECTION
image

## FIFTH SECTION
image

## LOADING FEATURE
image

# TODO
- Create async function to POST the question data to the database.

### CODE REVIEW

**Review by svaldes1 — APPROVED** [review]
Looks good!

**Review by SamLonneman — APPROVED** [review]
Gorgeous

**Review by svaldes1 — APPROVED** [review]
goated

**Review by SamLonneman — APPROVED** [review]
good good good

**Comment by SamLonneman** [comment]
Bro i don't get it, I literally just reviewed, how is my review stale :(

**Comment by svaldes1** [comment]
merging is crazy

**Comment by svaldes1** [comment]
it might technically wait for a 3rd person (rahul, since he has access) to approve it

bruh

**Comment by TheAndreiUrsu** [comment]
bruh thats crazy

**Pull request closed without merging**
